# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.7.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: build
        run: |
         ls
         cl /EHsc main.cpp
         echo OK
         ls
         main
         
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
         name: main
         path: main.exe
         
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Notify
        uses: appleboy/telegram-action@0.0.3
        
      - name: send
        uses: appleboy/telegram-action@master
#         run: echo &TELEGRAM_TOKEN_DEBUG
        with:
          to: ${{ TELEGRAM_TO_DEBUG }}
          token: ${{ TELEGRAM_TOKEN_DEBUG }}
          message: my test

      
